## Enables Prometheus monitoring for the router.
## Layer this on top of base.values.yaml to enable metrics collection.

router:
  monitoring:
    interval: "10s"
    prometheus:
      enabled: true
      auth:
        enabled: false
