apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Use the CPU offloading base to form a tiered cache structure: HBM - CPU - storage.
  - ../../cpu/base

labels:
  - pairs:
      llm-d.ai/guide: tiered-prefix-cache
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-vllm.yaml
