apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../recipes/modelserver/base/single-host/default

namePrefix: optimized-baseline-rocm-sglang-

components:
  - ../../../../recipes/modelserver/components/images/amd-sglang

labels:
  - pairs:
      llm-d.ai/guide: optimized-baseline
      llm-d.ai/model: Qwen3-32B
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: amd
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-sglang.yaml
