apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: modelserver
          image: ghcr.io/llm-d/llm-d-cuda:v0.7.0-rc.3
          command: ["/bin/sh", "-c"]
            # NOTE: The connector package version must match the vLLM version.
            # For vLLM 0.X.x use llmd-fs-connector==0.X.
          args:
           # We have 2 wheels released for vllm-0.19, install CUDA-13 wheel from https://github.com/llm-d/llm-d-kv-cache/commit/793b51ebcc9ae47d02c8317ff0db8c5f8ef5d81f
            - |
              mkdir -p /tmp/custom-package; \
              uv pip install --target /tmp/custom-package https://raw.githubusercontent.com/llm-d/llm-d-kv-cache/main/kv_connectors/llmd_fs_backend/wheels/llmd_fs_connector-0.19+cu130-cp312-cp312-linux_x86_64.whl; \
              export PYTHONPATH="/tmp/custom-package:$PYTHONPATH";
              exec vllm serve \
                Qwen/Qwen3-32B \
                --tensor-parallel-size 2 \
                --max-num-seq 1024 \
                --kv-transfer-config '{
                  "kv_connector":"MultiConnector",
                  "kv_role":"kv_both",
                  "kv_connector_extra_config": {
                    "connectors": [
                      {
                        "kv_connector": "OffloadingConnector",
                        "kv_role": "kv_both",
                        "kv_connector_extra_config": {
                          "cpu_bytes_to_use": 64424509440,
                          "lazy_offload": true
                        }
                      },
                      {
                        "kv_connector": "OffloadingConnector",
                        "kv_role": "kv_both",
                        "kv_connector_extra_config":
                        {
                          "spec_name": "SharedStorageOffloadingSpec",
                          "shared_storage_path": "/mnt/files-storage/",
                          "block_size": 256,
                          "threads_per_gpu": 64,
                          "spec_module_path": "llmd_fs_backend.spec"
                        }
                      }
                    ]
                  }
                }'
          env:
            - name: PYTHONHASHSEED
              value: "42"
          resources:
            limits:
              cpu: '16'
              memory: 400Gi
              nvidia.com/gpu: 2
            requests:
              cpu: '8'
              memory: 400Gi
              nvidia.com/gpu: 2
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.local
              name: pip-user-site
            - mountPath: /mnt/files-storage
              name: files-storage
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: pip-user-site
          emptyDir: {}
        - name: files-storage
          persistentVolumeClaim:
            claimName: llm-d-kv-cache-storage
