apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/llm-d/llm-d-workload-variant-autoscaler/config/overlays/namespace-scoped/openshift?ref=main
  - ../../base

patches:
  - path: servicemonitor-label-patch.yaml
    target:
      kind: ServiceMonitor
      name: wva-controller-manager-metrics-monitor
