apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
  - name: vllm/vllm-openai
    newName: 763104351884.dkr.ecr.us-east-1.amazonaws.com/vllm
    newTag: 0.23.0-gpu-py312-cu130-ubuntu22.04-ec2

patches:
  - path: patch-decode.yaml
  - path: patch-prefill.yaml
  - target:
      kind: Deployment
      name: decode
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/vpc.amazonaws.com~1efa
        value: "8"
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/vpc.amazonaws.com~1efa
        value: "8"
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/cpu
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node.kubernetes.io/instance-type: p5en.48xlarge
  - target:
      kind: Deployment
      name: prefill
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/vpc.amazonaws.com~1efa
        value: "2"
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/vpc.amazonaws.com~1efa
        value: "2"
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/cpu
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node.kubernetes.io/instance-type: p5en.48xlarge
