apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefill
spec:
  template:
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: llm-d.ai/model
                    operator: In
                    values:
                      - gpt-oss-120b
                  - key: llm-d.ai/guide
                    operator: In
                    values:
                      - pd-disaggregation
              topologyKey: topology.kubernetes.io/zone
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    llm-d.ai/role: "decode"
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: modelserver
          command: ["vllm", "serve"]
          args:
            - "openai/gpt-oss-120b"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
            - "--tensor-parallel-size=1"
            - "--block-size=128"
            - "--kv-transfer-config"
            - '{"kv_connector":"NixlConnector","kv_role":"kv_both","kv_connector_extra_config":{"backends":["LIBFABRIC"]}}'
            - "--no-disable-hybrid-kv-cache-manager"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
