apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: Deployment
      name: decode
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/rdma~1ib
        value: "2"
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/rdma~1ib
        value: "2"
