apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vllm

namePrefix: precise-prefix-cache-routing-tpu-v7-vllm-

# TODO(#1893): Replace with tpu-vllm component once Ironwood variant is in centralized tpu-vllm.
images:
  - name: REPLACE_MODEL_SERVER_IMAGE
    newName: vllm/vllm-tpu
    newTag: v0.13.2-ironwood

labels:
  - pairs:
      llm-d.ai/guide: precise-prefix-cache-routing
      llm-d.ai/model: Qwen3-Coder-480B-A35B-Instruct-FP8
      llm-d.ai/accelerator-variant: tpu
      llm-d.ai/accelerator-vendor: google
    includeSelectors: true
    includeTemplates: true
    fields:
      - version: v1
        kind: ServiceAccount
        path: metadata/labels
        create: true
      - group: leaderworkerset.x-k8s.io
        version: v1
        kind: LeaderWorkerSet
        path: metadata/labels
        create: true
      - group: leaderworkerset.x-k8s.io
        version: v1
        kind: LeaderWorkerSet
        path: spec/leaderWorkerTemplate/workerTemplate/metadata/labels
        create: true
      - group: monitoring.coreos.com
        version: v1
        kind: PodMonitor
        path: metadata/labels
        create: true
      - group: monitoring.coreos.com
        version: v1
        kind: PodMonitor
        path: spec/selector/matchLabels
        create: true

patches:
  - path: patch-vllm.yaml
