apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # gateway of choice
  - ../../../recipes/gateway/istio
  # modelserver
  - modelserver/coreweave

helmCharts:
  - name: inferencepool
    repo: oci://registry.k8s.io/gateway-api-inference-extension/charts
    version: v1.4.0
    releaseName: llm-d-infpool
    valuesFile: inferencepool.values.yaml
