apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - path: patch-vllm.yaml
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: decode
      spec:
        selector:
          matchLabels:
            llm-d.ai/model: gpt-oss-120b
        template:
          metadata:
            labels:
              llm-d.ai/model: gpt-oss-120b
