apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
  - name: vllm/vllm-openai
    newName: vllm/vllm-openai
    newTag: v0.22.0

patches:
  - path: patch-vllm-gpt120b.yaml
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: decode
      spec:
        selector:
          matchLabels:
            llm-d.ai/model: gpt-oss-120b
        template:
          metadata:
            labels:
              llm-d.ai/model: gpt-oss-120b
