apiVersion: apps/v1
kind: Deployment
metadata:
  name: encode
  labels:
    llm-d.ai/role: encode
spec:
  selector:
    matchLabels:
      llm-d.ai/role: encode
  template:
    metadata:
      labels:
        llm-d.ai/role: encode
    spec:
      serviceAccountName: sa
      containers:
        - name: modelserver
          image: REPLACE_MODEL_SERVER_IMAGE
          command: []
          args: []
          env: []
          ports:
            - name: modelserver
              containerPort: 8000
              protocol: TCP
            - name: ec-nixl
              containerPort: 5610
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: modelserver
          readinessProbe:
            httpGet:
              path: /v1/models
              port: modelserver
          startupProbe:
            httpGet:
              path: /v1/models
              port: modelserver
