apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: LeaderWorkerSet
      name: ".*-prefill"
    patch: |-
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/-
        value:
          name: OFFLOADING_MODE
          value: "cpu"
