apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../optimized-baseline/modelserver/amd/vllm/base

labels:
  - pairs:
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: amd
    includeSelectors: true
    includeTemplates: true

patches:
  - path: patch-vllm.yaml
