apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefill
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: modelserver
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen3-VL-32B-Instruct"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
            - "--tensor-parallel-size=4"
            - "--block-size=128"
            - "--trust-remote-code"
            - "--kv-transfer-config"
            - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
            - "--no-disable-hybrid-kv-cache-manager"
            - "--ec-transfer-config"
            - '{"ec_connector": "ECCPUConnector", "ec_role": "ec_consumer"}'
          env:
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
            # Workaround for https://github.com/vllm-project/vllm/issues/44548, required with vLLM v0.20.0+ due to torch 2.11
            - name: USER
              value: llm-d
          resources:
            limits:
              cpu: "8"
              memory: 256Gi
              nvidia.com/gpu: "4"
            requests:
              cpu: "8"
              memory: 128Gi
              nvidia.com/gpu: "4"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.config
              name: config-cache
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: config-cache
          emptyDir: {}
