apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 3
  template:
    spec:
      initContainers:
        - name: routing-proxy
          args:
            - --port=8000
            - --vllm-port=8200
            - --kv-connector=nixlv2
            - --ec-connector=ec-nixl
            - --zap-log-level=1
            - --secure-proxy=false
      containers:
        - name: modelserver
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen3-VL-32B-Instruct"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
            - "--tensor-parallel-size=2"
            - "--mm-processor-cache-gb"
            - "20"
            - "--kv-transfer-config"
            - '{"kv_connector":"NixlConnector", "kv_role":"kv_both", "kv_connector_extra_config": {"kv_lease_duration": 300}}'
            - "--no-disable-hybrid-kv-cache-manager"
            - "--port=8200"
          env:
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
            # Workaround for https://github.com/vllm-project/vllm/issues/44548, required with vLLM v0.20.0+ due to torch 2.11
            - name: USER
              value: llm-d
          resources:
            limits:
              cpu: "16"
              memory: 256Gi
              nvidia.com/gpu: "2"
              rdma/ib: "1"
            requests:
              cpu: "16"
              memory: 256Gi
              nvidia.com/gpu: "2"
              rdma/ib: "1"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.config
              name: config-cache
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: config-cache
          emptyDir: {}
