serviceAccountOverride: "default"

multinode: false

modelArtifacts:
  uri: "hf://Qwen/Qwen3-32B"
  name: "Qwen/Qwen3-32B"
  size: 80Gi
  authSecretName: "llm-d-hf-token"
  labels:
    llm-d.ai/inference-serving: "true"
    llm-d.ai/guide: "pd-disaggregation"
    llm-d.ai/accelerator-variant: "gpu"
    llm-d.ai/accelerator-vendor: "nvidia"
    llm-d.ai/model: "Qwen3-32B"

routing:
  servicePort: 8000
  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.7.1
    connector: nixlv2
    secure: false

accelerator:  # controls specialized hardware Type
  type: nvidia

decode:
  create: true
#  priorityClassName: nightly-gpu-critical
  replicas: 2
  initContainers:
    - name: preprocess
      image: ghcr.io/llm-d/llm-d-benchmark:v0.5.2
      imagePullPolicy: Always
      command: ["set_llmdbench_environment.py", "-e", "/shared-config/llmdbench_env.sh", "-i"]
      env:
        - name: NCCL_EXCLUDE_IB_HCA
          value: "mlx5_0,mlx5_2,mlx5_4,mlx5_8,mlx5_7,mlx5_10,mlx5_12,mlx5_14,mlx5_16"
      volumeMounts:
      - name: shared-config
        mountPath: /shared-config
  parallelism:
    tensor: 2
  podAnnotations:
    k8s.v1.cni.cncf.io/networks: "multi-nic-compute"
  containers:
  - name: "vllm"
    image: ghcr.io/llm-d/llm-d-cuda:v0.6.0
    modelCommand: custom
    command:
      - /bin/bash
      - -c
    args:
      - |
        source /shared-config/llmdbench_env.sh; vllm serve Qwen/Qwen3-32B \
        --host 0.0.0.0 \
        --served-model-name Qwen/Qwen3-32B \
        --port $VLLM_METRICS_PORT \
        --block-size $VLLM_BLOCK_SIZE \
        --max-model-len $VLLM_MAX_MODEL_LEN \
        --tensor-parallel-size $TP_SIZE \
        --kv-transfer-config "{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\"}" \
        --no-enable-log-requests \
        --disable-uvicorn-access-log
    env:
      - name: NCCL_EXCLUDE_IB_HCA
        value: "mlx5_0,mlx5_2,mlx5_4,mlx5_8,mlx5_7,mlx5_10,mlx5_12,mlx5_14,mlx5_16"
      - name: VLLM_BLOCK_SIZE
        value: "128"
      - name: VLLM_MAX_MODEL_LEN
        value: "32000"
      - name: VLLM_INFERENCE_PORT
        value: "8000"
      - name: VLLM_METRICS_PORT
        value: "8200"
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: UCX_TLS
        value: "sm,cuda_ipc,cuda_copy,tcp"
      - name: UCX_SOCKADDR_TLS_PRIORITY
        value: "tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: POD_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
    ports:
      - containerPort: 8200
        name: vllm
        protocol: TCP
    resources:
      limits:
        cpu: "32"
        memory: 128Gi
        # note: GPU resources get controlled by parallelism + accelerators above
        rdma/roce_gdr: "2"
      requests:
        cpu: "32"
        memory: 128Gi
        # note: GPU resources get controlled by parallelism + accelerators above
        rdma/roce_gdr: "2"
    extraConfig:
      startupProbe:
        httpGet:
          path: /health
          port: 8000
        failureThreshold: 60
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
      livenessProbe:
        tcpSocket:
          port: 8000
        failureThreshold: 3
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        failureThreshold: 3
        periodSeconds: 5
      securityContext:
        capabilities:
          add:
          - "IPC_LOCK"
          - "SYS_RAWIO"
          - "NET_ADMIN"
          - "NET_RAW"
        runAsGroup: 0
        runAsUser: 0
      imagePullPolicy: Always
    volumeMounts:
      - name: metrics-volume
        mountPath: /.config
      - name: shm
        mountPath: /dev/shm
      - name: torch-compile-cache
        mountPath: /.cache
      - name: shared-config
        mountPath: /shared-config
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
    - name: shared-config
      emptyDir: {}
    - name: metrics-volume
      emptyDir: {}
    - name: torch-compile-cache
      emptyDir: {}

prefill:
  create: true
#  priorityClassName: nightly-gpu-critical
  replicas: 1
  initContainers:
    - name: preprocess
      image: ghcr.io/llm-d/llm-d-benchmark:v0.5.2
      imagePullPolicy: Always
      command: ["set_llmdbench_environment.py", "-e", "/shared-config/llmdbench_env.sh", "-i"]
      env:
        - name: NCCL_EXCLUDE_IB_HCA
          value: "mlx5_0,mlx5_2,mlx5_4,mlx5_8,mlx5_7,mlx5_10,mlx5_12,mlx5_14,mlx5_16"
      volumeMounts:
      - name: shared-config
        mountPath: /shared-config
  parallelism:
    tensor: 2
  podAnnotations:
    k8s.v1.cni.cncf.io/networks: "multi-nic-compute"
  containers:
  - name: "vllm"
    image: ghcr.io/llm-d/llm-d-cuda:v0.6.0
    modelCommand: custom
    command:
      - /bin/bash
      - -c
    args:
     - |
        source /shared-config/llmdbench_env.sh; vllm serve Qwen/Qwen3-32B \
        --host 0.0.0.0 \
        --served-model-name Qwen/Qwen3-32B \
        --port $VLLM_INFERENCE_PORT \
        --block-size $VLLM_BLOCK_SIZE \
        --max-model-len $VLLM_MAX_MODEL_LEN \
        --tensor-parallel-size $TP_SIZE \
        --kv-transfer-config "{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\"}" \
        --no-enable-log-requests \
        --disable-uvicorn-access-log \
        --no-enable-prefix-caching
    env:
      - name: NCCL_EXCLUDE_IB_HCA
        value: "mlx5_0,mlx5_2,mlx5_4,mlx5_8,mlx5_7,mlx5_10,mlx5_12,mlx5_14,mlx5_16"
      - name: VLLM_BLOCK_SIZE
        value: "128"
      - name: VLLM_MAX_MODEL_LEN
        value: "32000"
      - name: VLLM_INFERENCE_PORT
        value: "8000"
      - name: VLLM_METRICS_PORT
        value: "8200"
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: UCX_TLS
        value: "sm,cuda_ipc,cuda_copy,tcp"
      - name: UCX_SOCKADDR_TLS_PRIORITY
        value: "tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: POD_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
    ports:
      - containerPort: 8000
        name: metrics
        protocol: TCP
    resources:
      limits:
        cpu: "32"
        memory: 128Gi
        # note: GPU resources get controlled by parallelism + accelerators above
        rdma/roce_gdr: "2"
      requests:
        cpu: "32"
        memory: 128Gi
        # note: GPU resources get controlled by parallelism + accelerators above
        rdma/roce_gdr: "2"
    extraConfig:
      startupProbe:
        httpGet:
          path: /health
          port: 8000
        failureThreshold: 60
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
      livenessProbe:
        tcpSocket:
          port: 8000
        failureThreshold: 3
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        failureThreshold: 3
        periodSeconds: 5
      securityContext:
        capabilities:
          add:
          - "IPC_LOCK"
          - "SYS_RAWIO"
          - "NET_ADMIN"
          - "NET_RAW"
        runAsGroup: 0
        runAsUser: 0
      imagePullPolicy: Always
    volumeMounts:
      - name: metrics-volume
        mountPath: /.config
      - name: shm
        mountPath: /dev/shm
      - name: torch-compile-cache
        mountPath: /.cache
      - name: shared-config
        mountPath: /shared-config
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
    - name: metrics-volume
      emptyDir: {}
    - name: torch-compile-cache
      emptyDir: {}
    - name: shared-config
      emptyDir: {}
