apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  template:
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: llm-d.ai/model
                    operator: In
                    values:
                      - gpt-oss-120b
                  - key: llm-d.ai/guide
                    operator: In
                    values:
                      - pd-disaggregation
              topologyKey: topology.kubernetes.io/zone
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    llm-d.ai/role: "prefill"
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: modelserver
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          env:
            - name: SGLANG_DISAGGREGATION_NIXL_BACKEND
              value: "LIBFABRIC"
