apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: controller-deployment-patch.yaml
    target:
      kind: Deployment
      name: wva-controller-manager
  - path: metrics-auth-rolebinding-patch.yaml
    target:
      kind: ClusterRoleBinding
      name: wva-metrics-auth-rolebinding
  - path: epp-token-secret-patch.yaml
    target:
      kind: Secret
      name: wva-epp-metrics-token
