apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../recipes/modelserver/base/single-host/pd/vllm
  - resource-claim-templates.yaml

namePrefix: pd-disaggregation-xpu-vllm-

configurations:
  - namereference.yaml

components:
  - ../../../../recipes/modelserver/components/images/xpu-vllm
  - ../../../../recipes/modelserver/components/images/routing-sidecar

labels:
  - pairs:
      llm-d.ai/model: Qwen3-0.6B
      llm-d.ai/guide: pd-disaggregation
      llm-d.ai/accelerator-variant: xpu
      llm-d.ai/accelerator-vendor: intel
      llm-d.ai/engine-type: vllm
    includeSelectors: true
    includeTemplates: true
    fields:
      - version: v1
        kind: ServiceAccount
        path: metadata/labels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: metadata/labels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/selector/matchLabels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/template/metadata/labels
        create: true
      - group: monitoring.coreos.com
        version: v1
        kind: PodMonitor
        path: metadata/labels
        create: true
      - group: monitoring.coreos.com
        version: v1
        kind: PodMonitor
        path: spec/selector/matchLabels
        create: true
patches:
  - path: patch-decode.yaml
  - path: patch-prefill.yaml
