apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mooncake
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mooncake-master-store
      app.kubernetes.io/component: master-store
      app.kubernetes.io/part-of: mooncake
    includeTemplates: true
    includeSelectors: true
