
inferenceExtension:
  extraServicePorts:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081

inferencePool:
  modelServers:
    matchLabels:
      llm-d.ai/guide: "tiered-prefix-cache-storage"
