apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - encode-statefulset.yaml
  - resource-claim-template.yaml

images:
  - name: REPLACE_XPU_MODEL_SERVER_IMAGE
    newName: ghcr.io/xiaojun-zhang/llm-d-xpu-sglang
    newTag: sglang-heterogeneous-e-pd
    digest: sha256:56ed840fe2890671a894fda14da1ead719ce18e5a94d3095a58ba5b54c41e55d
