apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../recipes/modelserver/base/single-host/default

namePrefix: agentic-serving-tpu-vllm-

# TODO(#1893): Replace with tpu-vllm component once nightly features are in a stable release.
images:
  - name: REPLACE_MODEL_SERVER_IMAGE
    newName: vllm/vllm-tpu
    newTag: nightly-20260501-8e706b2-941fb50

labels:
  - pairs:
      llm-d.ai/guide: agentic-serving
      llm-d.ai/model: Qwen3-Coder-480B-A35B-Instruct-FP8
      llm-d.ai/accelerator-variant: tpu
      llm-d.ai/accelerator-vendor: google
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-vllm.yaml
