apiVersion: apps/v1
kind: Deployment
metadata:
  name: encode
  labels:
    llm-d.ai/role: encode
spec:
  replicas: 2
  selector:
    matchLabels:
      llm-d.ai/role: encode
  template:
    metadata:
      labels:
        llm-d.ai/role: encode
    spec:
      serviceAccountName: sa
      containers:
        - name: modelserver
          image: REPLACE_MODEL_SERVER_IMAGE
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen3-VL-32B-Instruct"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
            - "--tensor-parallel-size=1"
            - "--trust-remote-code"
            - "--mm-encoder-only"
            - "--enforce-eager"
            - "--no-enable-prefix-caching"
            - "--ec-transfer-config"
            - '{"ec_connector": "ECCPUConnector", "ec_role": "ec_producer"}'
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
          ports:
            - name: modelserver
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "8"
              memory: 32Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "8"
              memory: 32Gi
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.config
              name: config-cache
          startupProbe:
            httpGet:
              path: /v1/models
              port: modelserver
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            httpGet:
              path: /health
              port: modelserver
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/models
              port: modelserver
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: config-cache
          emptyDir: {}
