apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../recipes/modelserver/base/single-host/default
  - resource-claim-template.yaml

namePrefix: mm-baseline-xpu-vllm-

components:
  - ../../base/vllm
  - ../../../../../recipes/modelserver/components/images/xpu-vllm

labels:
  - pairs:
      llm-d.ai/model: Qwen3-VL-32B-Instruct
      llm-d.ai/guide: multimodal-optimized-baseline
      llm-d.ai/accelerator-variant: xpu
      llm-d.ai/accelerator-vendor: intel
    includeSelectors: true
    includeTemplates: true

patches:
  - path: patch-vllm.yaml
