apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 2
  template:
    spec:
      securityContext:
        fsGroup: 107
        supplementalGroups:
          - 107
      containers:
        - name: modelserver
          resources:
            limits:
              cpu: "8"
              memory: 24Gi
            requests:
              cpu: "4"
              memory: 12Gi
            claims:
              - name: intel-decode-claim
      resourceClaims:
        - name: intel-decode-claim
          resourceClaimTemplateName: intel-claim-template-decode
