apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: LeaderWorkerSet
    patch: |-
      - op: replace
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/5
        value:
          name: ENABLE_MTP
          value: "0"
