apiVersion: llm-d.ai/v1alpha2
kind: InferenceObjective
metadata:
  name: premium-traffic
  labels:
    llm-d.ai/guide: "flow-control"
    llm-d.ai/inference-serving: "true"
    llm-d.ai/model: "Qwen3-32B"
spec:
  priority: 100
  poolRef:
    name: default-pool
---
apiVersion: llm-d.ai/v1alpha2
kind: InferenceObjective
metadata:
  name: standard-traffic
  labels:
    llm-d.ai/guide: "flow-control"
    llm-d.ai/inference-serving: "true"
    llm-d.ai/model: "Qwen3-32B"
spec:
  priority: 0
  poolRef:
    name: default-pool
---
apiVersion: llm-d.ai/v1alpha2
kind: InferenceObjective
metadata:
  name: best-effort-traffic
  labels:
    llm-d.ai/guide: "flow-control"
    llm-d.ai/inference-serving: "true"
    llm-d.ai/model: "Qwen3-32B"
spec:
  priority: -10
  poolRef:
    name: default-pool
