#!/usr/bin/env python3
"""Generate DisaggregatedSet manifest from legacy LeaderWorkerSet role manifests."""

from __future__ import annotations

import argparse
import copy
import sys
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("PyYAML is required: pip install pyyaml") from exc


STANDARD_LABELS = {
    "llm-d.ai/model": "DeepSeek-R1-0528",
    "llm-d.ai/guide": "wide-ep-lws",
    "llm-d.ai/accelerator-variant": "gpu",
    "llm-d.ai/accelerator-vendor": "nvidia",
}


class LiteralSafeDumper(yaml.SafeDumper):
    """Safe YAML dumper that keeps multi-line shell strings readable."""


def str_representer(dumper: yaml.Dumper, data: str) -> yaml.ScalarNode:
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


LiteralSafeDumper.add_representer(str, str_representer)


def load_lws(path: Path) -> dict:
    with path.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def role_from_lws(lws: dict, role_name: str, common_labels: dict) -> dict:
    metadata_labels = copy.deepcopy(common_labels)
    metadata_labels.update(lws.get("metadata", {}).get("labels", {}))
    metadata_labels["llm-d.ai/role"] = role_name

    return {
        "name": role_name,
        "metadata": {"labels": metadata_labels},
        "spec": copy.deepcopy(lws["spec"]),
    }


def build_disaggregatedset(decode_lws: dict, prefill_lws: dict) -> dict:
    return {
        "apiVersion": "disaggregatedset.x-k8s.io/v1",
        "kind": "DisaggregatedSet",
        "metadata": {
            "name": "wide-ep-lws-nvidia-gpu-vllm",
            "labels": copy.deepcopy(STANDARD_LABELS),
        },
        "spec": {
            "roles": [
                role_from_lws(prefill_lws, "prefill", STANDARD_LABELS),
                role_from_lws(decode_lws, "decode", STANDARD_LABELS),
            ],
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--base-dir",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "base",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "disaggregatedset"
        / "disaggregatedset.yaml",
    )
    args = parser.parse_args()

    decode_lws = load_lws(args.base_dir / "decode.yaml")
    prefill_lws = load_lws(args.base_dir / "prefill.yaml")
    manifest = build_disaggregatedset(decode_lws, prefill_lws)

    header = (
        "# Generated by scripts/generate-disaggregatedset.py from base/decode.yaml "
        "and base/prefill.yaml.\n"
        "# Re-run the generator after changing legacy LWS role specs.\n"
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as handle:
        handle.write(header)
        yaml.dump(
            manifest,
            handle,
            Dumper=LiteralSafeDumper,
            default_flow_style=False,
            sort_keys=False,
            width=120,
        )

    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
