apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
        cloud.google.com/gke-tpu-topology: "2x4"
      containers:
        - name: modelserver
          resources:
            requests:
              google.com/tpu: "8"
            limits:
              google.com/tpu: "8"
