apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: llm-d-inference-gateway-telemetry
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: llm-d-inference-gateway
  accessLogging:
    - providers:
        - name: envoy
