apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../recipes/modelserver/base/single-host/default


namePrefix: precise-prefix-cache-routing-gpu-vllm-

images:
  - name: REPLACE_MODEL_SERVER_IMAGE
    newName: vllm/vllm-openai
    newTag: v0.19.1

labels:
  - pairs:
      llm-d.ai/guide: precise-prefix-cache-routing
      llm-d.ai/model: Qwen3-32B
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: nvidia
    includeSelectors: true
    includeTemplates: true
    fields:
      - version: v1
        kind: ServiceAccount
        path: metadata/labels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: metadata/labels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/selector/matchLabels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/template/metadata/labels
        create: true
      - group: monitoring.coreos.com
        version: v1
        kind: PodMonitor
        path: metadata/labels
        create: true
      - group: monitoring.coreos.com
        version: v1
        kind: PodMonitor
        path: spec/selector/matchLabels
        create: true
patches:
  - path: patch-vllm.yaml
