inferenceExtension:
  replicas: 1
  flags:
  image:
    # both downstream infernece-scheduler and upstream epp image can support simulated-accelerators example
    ###################
    name: llm-d-inference-scheduler
    hub: ghcr.io/llm-d
    tag: v0.6.0
    ###################
    # name: epp
    # hub: registry.k8s.io/gateway-api-inference-extension
    # tag: v1.4.0
    ###################
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "default-plugins.yaml"  # using upstream GIE default-plugins, see: https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/config/charts/inferencepool/templates/epp-config.yaml#L7C3-L56C33

  # Distributed tracing configuration (OpenTelemetry)
  tracing:
    enabled: false
    # otelExporterEndpoint: "http://otel-collector:4317"
    # sampling:
    #   sampler: "parentbased_traceidratio"
    #   samplerArg: "0.1"
  # Monitoring configuration for EPP
  monitoring:
    interval: "10s"
    prometheus:
      enabled: true
      auth:
        enabled: true
        secretName: sim-gateway-sa-metrics-reader-secret
inferencePool:
  targetPorts:
    - number: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inference-serving: "true"
      llm-d.ai/guide: "simulated-accelerators"
      # optional additional guide-specific labels - no overlays so we can be specific here
      llm-d.ai/accelerator-variant: "cpu"
      llm-d.ai/model: "random"
