apiVersion: fma.llm-d.ai/v1alpha1
kind: InferenceServerConfig
metadata:
  name: fma-isc
spec:
  modelServerConfig:
    port: 8000
    options: "--model Qwen/Qwen3-0.6B --enable-sleep-mode --gpu-memory-utilization 0.9"
    env_vars:
      VLLM_LOGGING_LEVEL: "INFO"
      HF_HOME: "/tmp/hf_cache"
    labels:
      llm-d.ai/guide: "fast-model-actuation"
      llm-d.ai/model: "qwen3-0.6b"
  launcherConfigName: "fma-launcher"
