router:
  extraServicePorts:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081

  epp:
    pluginsConfigFile: "e-p-d-config.yaml"
    pluginsCustomConfig:
      e-p-d-config.yaml: |
        apiVersion: llm-d.ai/v1alpha1
        kind: EndpointPickerConfig
        plugins:
        - type: disagg-headers-handler
        - type: always-disagg-multimodal-decider
        - type: always-disagg-pd-decider
        - type: disagg-profile-handler
          parameters:
            deciders:
              encode: always-disagg-multimodal-decider
              prefill: always-disagg-pd-decider
        - type: encode-filter
        - type: prefill-filter
        - type: decode-filter
        - type: prefix-cache-scorer
        - type: queue-scorer
        - type: kv-cache-utilization-scorer
        - type: active-request-scorer
        - type: no-hit-lru-scorer
        - type: token-producer
          parameters:
            estimate:
              image:
                mode: dynamic
                defaultResolution:
                  width: 1280
                  height: 720
                dynamic:
                  factor: 1024
        - type: approx-prefix-cache-producer
        - type: max-score-picker
        schedulingProfiles:
        - name: encode
          plugins:
          - pluginRef: encode-filter
          - pluginRef: queue-scorer
            weight: 2
          - pluginRef: max-score-picker
        - name: prefill
          plugins:
          - pluginRef: prefill-filter
          - pluginRef: prefix-cache-scorer
            weight: 3
          - pluginRef: queue-scorer
            weight: 2
          - pluginRef: kv-cache-utilization-scorer
            weight: 2
        - name: decode
          plugins:
          - pluginRef: decode-filter
          - pluginRef: queue-scorer
            weight: 2
          - pluginRef: kv-cache-utilization-scorer
            weight: 2
          - pluginRef: prefix-cache-scorer
            weight: 3
          - pluginRef: no-hit-lru-scorer
            weight: 2
          - pluginRef: max-score-picker

  modelServers:
    matchLabels:
      llm-d.ai/guide: "e-disaggregation"
