{{- define "gkemonitoring.name" -}}
{{- .Values.gaieHelmName | default "default-pool" | lower | trim | trunc 40 -}}-epp
{{- end -}}
{{- define "gkemonitoring.labels" -}}
app.kubernetes.io/name: {{ include "gkemonitoring.name" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
{{- end -}}
{{- define "gkemonitoring.selectorLabels" -}}
inferencepool: {{ include "gkemonitoring.name" . }}
{{- end -}}

{{- $metricsReadSA := printf "%s-metrics-reader-sa" .Release.Name -}}
{{- $metricsReadSecretName := printf "%s-metrics-reader-secret" .Release.Name -}}
{{- $metricsReadRoleName := printf "%s-%s-metrics-reader" .Release.Namespace .Release.Name -}}
{{- $metricsReadRoleBindingName := printf "%s-%s-metrics-reader-role-binding" .Release.Namespace .Release.Name -}}
{{- $secretReadRoleName := printf "%s-metrics-reader-secret-read" .Release.Name -}}
{{- $gmpNamespace := "gmp-system" -}}
{{- $isAutopilot := false -}}
{{- with .Values.provider.gke }}
  {{- $isAutopilot = .autopilot | default false -}}
{{- end }}
{{- if $isAutopilot -}}
{{-   $gmpNamespace = "gke-gmp-system" -}}
{{- end -}}
{{- $gmpCollectorRoleBindingName := printf "%s:collector:%s-%s-metrics-reader-secret-read" $gmpNamespace .Release.Namespace .Release.Name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $metricsReadSA }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $metricsReadSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gkemonitoring.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ $metricsReadSA }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $metricsReadRoleName }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $metricsReadRoleBindingName }}
subjects:
- kind: ServiceAccount
  name: {{ $metricsReadSA }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $metricsReadRoleName }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $secretReadRoleName }}
rules:
- resources:
  - secrets
  apiGroups: [""]
  verbs: ["get", "list", "watch"]
  resourceNames: [{{ $metricsReadSecretName | quote }}]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $gmpCollectorRoleBindingName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  name: {{ $secretReadRoleName }}
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: collector
  namespace: {{ $gmpNamespace }}
  kind: ServiceAccount
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gkemonitoring.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: metrics
    scheme: http
    interval: {{ .Values.inferenceExtension.monitoring.interval }}
    path: /metrics
    authorization:
      type: Bearer
      credentials:
        secret:
          name: {{ $metricsReadSecretName }}
          key: token
  selector:
    matchLabels:
      {{- include "gkemonitoring.selectorLabels" . | nindent 8 }}
---
# for vllm server promethues
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ .Release.Name }}-vllm
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
  - port: 8000
    scheme: http
    interval: 15s
    path: /metrics
  selector:
    matchLabels:
      llm-d.ai/model: ms-kv-events-llm-d-modelservice # hard code here, will need to revisit

