apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# 3 prefill workers (DEP8) + 1 decode worker (DEP16, 4 nodes) -> 10 nodes / 40 GPUs.
patches:
  - target:
      kind: LeaderWorkerSet
      name: ".*-prefill"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: LeaderWorkerSet
      name: ".*-decode"
    patch: |-
      - op: replace
        path: /spec/leaderWorkerTemplate/size
        value: 4
