apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: modelserver
          command: ["python3", "-m", "sglang.launch_server"]
          args:
            - "--model-path=openai/gpt-oss-120b"
            - "--port=8200"
            - "--host=0.0.0.0"
            - "--disaggregation-mode=decode"
            - "--disaggregation-transfer-backend=nixl"
            - "--tensor-parallel-size=4"
            - "--log-level=info"
            - "--enable-metrics"
            - "--uvicorn-access-log-exclude-prefixes=/metrics"
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
          resources:
            limits:
              cpu: "16"
              memory: 64Gi
              nvidia.com/gpu: "4"
            requests:
              cpu: "16"
              memory: 64Gi
              nvidia.com/gpu: "4"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - name: metrics-volume
              mountPath: /.config
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: metrics-volume
          emptyDir: {}
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "16Gi"
