inferenceExtension:
  replicas: 1
  flags:
  image:
    # both downstream infernece-scheduler and upstream epp image can support inference-scheduling example
    ###################
    name: llm-d-inference-scheduler
    hub: ghcr.io/llm-d
    tag: v0.6.0
    ###################
    # name: epp
    # hub: registry.k8s.io/gateway-api-inference-extension
    # tag: v1.4.0
    ###################
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "default-plugins.yaml"
  # Distributed tracing configuration (OpenTelemetry)
  tracing:
    enabled: false
    # otelExporterEndpoint: "http://otel-collector:4317"
    # sampling:
    #   sampler: "parentbased_traceidratio"
    #   samplerArg: "0.1"
  monitoring:
    interval: "10s"
    prometheus:
      enabled: true
      auth:
        secretName: inference-scheduling-gateway-sa-metrics-reader-secret
inferencePool:
  targetPorts:
    - number: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inference-serving: "true"
      llm-d.ai/guide: "inference-scheduling"
