apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../recipes/modelserver/base/single-host/e-pd

namePrefix: e-pd-disaggregation-nvidia-gpu-vllm-

components:
  - ../../../../../../../recipes/modelserver/components/images/routing-sidecar/nightly
  - ../../../../../../../recipes/modelserver/components/images/gpu-vllm/ec-connector

labels:
  - pairs:
      llm-d.ai/model: Qwen3-VL-32B-Instruct
      llm-d.ai/guide: e-disaggregation
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: nvidia
      llm-d.ai/engine-type: vllm
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-encode.yaml
  - path: patch-decode.yaml
