apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: modelserver
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen3-8B"
            - "--disable-uvicorn-access-log"
            - "--tensor-parallel-size=4"
            - "--enforce-eager"
            - "--gpu-memory-utilization=0.9"
            - "--kv-transfer-config"
            - '{"kv_connector":"NixlConnector","kv_role":"kv_both","kv_buffer_device":"cpu"}'
            - "--port=8200"
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
            - name: OMPI_MCA_btl_vader_single_copy_mechanism
              value: "none"
            - name: HABANA_LOGS
              value: "/tmp/habana_logs"
            - name: UCX_TLS
              value: "tcp"
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VLLM_NIXL_SIDE_CHANNEL_PORT
              value: "5600"
            - name: VLLM_LOGGING_LEVEL
              value: "DEBUG"
            - name: VLLM_SKIP_WARMUP
              value: "true"
            - name: PT_HPU_LAZY_MODE
              value: "1"
            - name: PT_HPU_ENABLE_LAZY_COLLECTIVES
              value: "true"
            - name: LD_LIBRARY_PATH
              value: "/usr/lib/nixl_ofi:/usr/local/lib:/usr/lib:/opt/amazon/openmpi/lib:/usr/lib/habanalabs"
            - name: DO_NOT_TRACK
              value: "1"
            - name: VLLM_USE_V1
              value: "1"
          resources:
            claims:
              - name: hpu-decode-claim
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
          startupProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 60
          livenessProbe:
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 20
          readinessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
      resourceClaims:
        - name: hpu-decode-claim
          resourceClaimTemplateName: hpu-decode-claim
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
        - name: torch-compile-cache
          emptyDir: {}
