apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        fsGroup: 107
        supplementalGroups:
          - 107
      containers:
        - name: modelserver
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              exec vllm serve \
                Qwen/Qwen3-32B \
                --dtype bfloat16 \
                --block-size 64 \
                --tensor-parallel-size=4 \
                --gpu-memory-utilization 0.85 \
                --max-num-seq 128 \
                --uvicorn-log-level warning
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
          resources:
            limits:
              cpu: '8'
              memory: 60Gi
            requests:
              cpu: '8'
              memory: 60Gi
            claims:
              - name: intel-decode-claim
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.config
              name: vllm-config
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      restartPolicy: Always
      enableServiceLinks: false
      terminationGracePeriodSeconds: 130
      resourceClaims:
        - name: intel-decode-claim
          resourceClaimTemplateName: tiered-prefix-cache-intel-claim-template-decode
      volumes:
        - name: data
          emptyDir: {}
        - name: shm
          emptyDir:
            medium: Memory
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: vllm-config
          emptyDir: {}
