apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefill
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: modelserver
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen3.5-397B-A17B-FP8"
            - "--max-model-len=9216"
            - "--max-num-batched-tokens=8192"
            - "--max-num-seqs=512"
            - "--tensor-parallel-size=8"
            - "--language-model-only"
            - "--limit-mm-per-prompt"
            - '{"image": 0, "video": 0}'
            - "--kv-cache-dtype=fp8"
            - "--enable-expert-parallel"
            - "--no-disable-hybrid-kv-cache-manager"
            - "--kv-transfer-config"
            - '{"kv_connector":"TPUConnectorHMA","kv_connector_module_path":"tpu_inference.distributed.tpu_connector_hma","kv_role":"kv_producer"}'
            - "--port=8000"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TPU_SIDE_CHANNEL_PORT
              value: "9600"
            - name: TPU_KV_TRANSFER_PORT
              value: "9100"
          ports:
            - containerPort: 9100
              name: tpu-kv-transfer
              protocol: TCP
            - containerPort: 9600
              name: tpu-pd-coord
              protocol: TCP
          resources:
            limits:
              cpu: "200"
              memory: 800Gi
              google.com/tpu: 4
            requests:
              cpu: "200"
              memory: 800Gi
              google.com/tpu: 4
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.config
              name: metrics-volume
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 240
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 100Gi
        - name: torch-compile-cache
          emptyDir: {}
        - name: metrics-volume
          emptyDir: {}
