apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../recipes/modelserver/base/single-host/pd/vllm

namePrefix: pd-disaggregation-rocm-vllm-

components:
  - ../../../../../recipes/modelserver/components/images/amd-vllm

labels:
  - pairs:
      llm-d.ai/model: Llama-3.3-70B-Instruct-FP8-KV
      llm-d.ai/guide: pd-disaggregation
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: amd
      llm-d.ai/engine-type: vllm
    includeSelectors: true
    includeTemplates: true
    fields:
      - version: v1
        kind: ServiceAccount
        path: metadata/labels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: metadata/labels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/selector/matchLabels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/template/metadata/labels
        create: true
      - group: monitoring.coreos.com
        version: v1
        kind: PodMonitor
        path: metadata/labels
        create: true
      - group: monitoring.coreos.com
        version: v1
        kind: PodMonitor
        path: spec/selector/matchLabels
        create: true
patches:
  - path: patch-decode.yaml
  - path: patch-prefill.yaml
