apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../recipes/modelserver/base/single-host/default

namePrefix: optimized-baseline-cpu-vllm-

components:
  - ../../../../recipes/modelserver/components/images/cpu-vllm

labels:
  - pairs:
      llm-d.ai/guide: optimized-baseline
      llm-d.ai/model: Qwen3-32B
      llm-d.ai/accelerator-variant: cpu
      llm-d.ai/accelerator-vendor: intel
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-vllm.yaml
