apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: REPLACE_MODEL_SERVER_IMAGE
    newName: vllm/vllm-openai
    newTag: v0.23.0

# Workaround for https://github.com/vllm-project/vllm/issues/44548, required with vLLM v0.20.0+ due to torch 2.11
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: USER
          value: llm-d
  - target:
      kind: LeaderWorkerSet
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: USER
          value: llm-d
