apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gke

patches:
  - target:
      kind: LeaderWorkerSet
    patch: |-
      - op: add
        path: /metadata/labels/kueue.x-k8s.io~1queue-name
        value: default
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/metadata/annotations/kueue.x-k8s.io~1podset-required-topology
        value: "cloud.google.com/gce-topology-block"
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/metadata/annotations/kueue.x-k8s.io~1podset-group-name
        value: "llm-d-wide-ep"
