apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vllm

namePrefix: pd-disaggregation-tpu-vllm-

images:
  - name: REPLACE_MODEL_SERVER_IMAGE
    newName: docker.io/vllm/vllm-tpu
    newTag: nightly-20260430-18ed615-5b39b26

labels:
  - pairs:
      llm-d.ai/model: Qwen3.5-397B-A17B-FP8
      llm-d.ai/guide: pd-disaggregation
      llm-d.ai/accelerator-variant: tpu
      llm-d.ai/accelerator-vendor: google
      llm-d.ai/engine-type: vllm
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-decode.yaml
  - path: patch-prefill.yaml
