apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base

labels:
  - pairs:
      llm-d.ai/guide: tiered-prefix-cache
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-vllm.yaml
