apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../recipes/modelserver/base/single-host/pd/vllm

namePrefix: pd-disaggregation-nvidia-gpu-vllm-

components:
  - ../../../../../recipes/modelserver/components/images/gpu-vllm
  - ../../../../../recipes/modelserver/components/images/routing-sidecar

labels:
  - pairs:
      llm-d.ai/model: gpt-oss-120b
      llm-d.ai/guide: pd-disaggregation
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: nvidia
      llm-d.ai/engine-type: vllm
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-decode.yaml
  - path: patch-prefill.yaml
